name: Lint

on: push

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
      - name: Run rubocop
        run: bundle exec rubocop --parallel
